# Mandatory
trigger_token: <openshift-ci trigger token>
processed_versions_file_path: <path to processed versions file>

# Optional
slack_webhook_url: <slack webhook url to post job status>
slack_errors_webhook_url: <slack webhook url to post code errors>
run_interval: 24h # can be s/m/h

versions:
  "4.13":
    - <openshift-ci-test-name-1>
    - <openshift-ci-test-name-2>
    - <openshift-ci-test-name-3>
  "4.12":
    - <openshift-ci-test-name-1>
    - <openshift-ci-test-name-2>
    - <openshift-ci-test-name-3>
